spring.application.name=security-demo
spring.datasource.url= jdbc:postgresql://localhost:5432/SecurityDemo
spring.datasource.username=postgres
spring.datasource.password=ebmebm017


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

application.security.jwt.secret-key=8e2d4f9a1c6b3e7f0a9d5b2c8e1f6a4b7d9c3e5f1a8b6d2c4e7f9a1b3d5c8e2
application.security.jwt.expiration=86400000

logging.level.org.springframework.security=Debug